#!/usr/bin/env python
"""Create symlink directory with `n` samples."""
import argparse
import os

from glob import glob
from random import sample
from os.path import join


def main(args):
    """Main."""
    files = glob(join(args.source, "*.xml"))
    sampled = sample(files, args.nmodels)
    for s in sampled:
        os.symlink(s, join(args.target, os.path.basename(s)))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("--log", default="INFO")
    parser.add_argument("source", type=str)
    parser.add_argument("target", type=str)
    parser.add_argument("-n", "--nmodels", type=int, default=10)

    _args = parser.parse_args()

    main(_args)