#!/usr/bin/env python
"""Create symlink directory with `n` samples."""
import argparse
import os

from glob import glob
from random import sample


def main(args):
    """Main."""
    files = glob(os.path.join(args.source, "*.xml"))
    file_names = [os.path.basename(f) for f in files]
    source_list = args.source.split(os.sep)
    target_list = args.target.split(os.sep)

    if not source_list[-1]:
        source_list.pop()
    if not target_list[-1]:
        target_list.pop()

    # move to common node
    while target_list[0] == source_list[0]:
        target_list.pop(0)
        source_list.pop(0)

    # add relative difference
    source_list = len(target_list) * [".."] + source_list

    relative_source = os.path.join(*source_list)
    relative_files = [os.path.join(relative_source, f) for f in file_names]

    os.makedirs(args.target)

    sampled = sample(relative_files, args.nmodels)
    for s in sampled:
        os.symlink(s, os.path.join(args.target, os.path.basename(s)))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("--log", default="INFO")
    parser.add_argument("source", type=str, help="Source directory with sbml models.")
    parser.add_argument(
        "target", type=str, help="Target directory is created and contains symlinks."
    )
    parser.add_argument("-n", "--nmodels", type=int, default=10)

    _args = parser.parse_args()

    main(_args)